language: php

php:
    - 7.0
    - 7.1
    - 7.2

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - pecl update-channels
    - pecl install trader
    - composer update --no-interaction --prefer-dist

script:
    - composer lint
    - composer phpunit-coverage

after_script:
    - |
        if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
